In [6]:
df["Diabetes_012"].value_counts().sort_index()

Diabetes_012
0.0    16874
1.0      374
2.0     2752
Name: count, dtype: int64

In [5]:
df.isnull().sum()

Diabetes_012            0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [4]:
df.describe()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,20000.0000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,0.2939,0.431650,0.425250,0.962250,28.478750,0.444650,0.040200,0.094150,0.759500,0.634250,...,0.952050,0.08490,2.510400,3.164400,4.238100,0.170000,0.443100,8.034100,5.056600,6.062550
std,0.6948,0.495319,0.494393,0.190596,6.544814,0.496939,0.196433,0.292045,0.427398,0.481652,...,0.213666,0.27874,1.072963,7.365432,8.768903,0.375642,0.496764,3.053851,0.978338,2.070954
min,0.0000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.0000,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,0.00000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.0000,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.00000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,0.0000,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.00000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,2.0000,1.000000,1.000000,1.000000,95.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.00000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Diabetes_012          20000 non-null  float64
 1   HighBP                20000 non-null  float64
 2   HighChol              20000 non-null  float64
 3   CholCheck             20000 non-null  float64
 4   BMI                   20000 non-null  float64
 5   Smoker                20000 non-null  float64
 6   Stroke                20000 non-null  float64
 7   HeartDiseaseorAttack  20000 non-null  float64
 8   PhysActivity          20000 non-null  float64
 9   Fruits                20000 non-null  float64
 10  Veggies               20000 non-null  float64
 11  HvyAlcoholConsump     20000 non-null  float64
 12  AnyHealthcare         20000 non-null  float64
 13  NoDocbcCost           20000 non-null  float64
 14  GenHlth               20000 non-null  float64
 15  MentHlth              20000 non-null  float64
 16  PhysHlth              20000 non-null  float64
 17  DiffWalk              20000 non-null  float64
 18  Sex                   20000 non-null  float64
 19  Age                   20000 non-null  float64
 20  Education             20000 non-null  float64
 21  Income                20000 non-null  float64
dtypes: float64(22)
memory usage: 3.4 MB

In [2]:
df = pd.read_csv("../data/processed/chronic_sample.csv")

print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

Dataset shape: (20000, 22)

First 5 rows:

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,0.0,0.0,1.0,21.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,3.0,7.0,0.0,0.0,7.0,4.0,2.0
1,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,13.0,6.0,6.0
2,0.0,0.0,0.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,4.0,7.0
3,0.0,0.0,0.0,1.0,27.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,3.0,0.0,0.0,1.0,2.0,4.0,7.0
4,0.0,0.0,1.0,1.0,31.0,1.0,0.0,0.0,0.0,1.0,...,1.0,1.0,4.0,27.0,27.0,1.0,0.0,8.0,3.0,2.0

In [1]:
import pandas as pd
import os

print("Working directory:", os.getcwd())

Working directory: c:\Users\kiafe\OneDrive\Documents\Desktop\demo proj\AI-Healthcare-Risk-Prediction\notebooks